version: '3.8'

services:
  tetris_backend:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/app
    command: npm run start:dev
    