version: '3.8'

services:
  tetris_backend:
    build:
      context: .
      target: test
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=dev
    env_file:
      - .env.secret
    volumes:
      - ./:/app
    command: npm run start:dev
    